version: "3.1"
services:

    php:
      build:
        context: .
        dockerfile: Dockerfile-www.dockerfile
      image: php-www
      tty: true
      env_file:
        - ./www.env
      container_name: ${PROJECT_NAME}-www
      working_dir: /var/www
      volumes:
        - www:/var/www
        - ./sourcefiles/www-php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/local.ini        
      restart: always
      networks:
            testing_net:
                ipv4_address: 180.28.1.2

    nginx:
      image: nginx
      container_name: ${PROJECT_NAME}-webserver
      tty: true
      working_dir: /var/www
      volumes:
        - www:/var/www
        - nginx-logs:/var/nginx-log/
        - ./sourcefiles/nginx:/etc/nginx/
      ports:
        - "${NGINX_HTTP_PORT}:80"
        - "${NGINX_HTTPS_PORT}:443"
      restart: always  
      networks:
            testing_net:
                ipv4_address: 180.28.1.3
                
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 180.28.0.0/16                
                
volumes:

  www:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/sourcefiles/www

  nginx-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/logs/nginx        